# Generated by Django 5.2.6 on 2025-10-25 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('schemes', '0002_scheme_custom_form_fields_scheme_form_template'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='application',
            name='form_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='schemes.scheme'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('APPLIED', 'Applied'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ON_HOLD', 'On Hold')], default='APPLIED', max_length=20),
        ),
        migrations.AlterModelTable(
            name='application',
            table='applications_application',
        ),
        migrations.CreateModel(
            name='ApplicationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('ID_PROOF', 'ID Proof'), ('ADDRESS_PROOF', 'Address Proof'), ('INCOME_CERTIFICATE', 'Income Certificate'), ('CASTE_CERTIFICATE', 'Caste Certificate'), ('EDUCATIONAL_CERTIFICATE', 'Educational Certificate'), ('MEDICAL_REPORT', 'Medical Report'), ('BANK_PASSBOOK', 'Bank Passbook'), ('PHOTO', 'Photograph'), ('OTHER', 'Other Document')], max_length=50)),
                ('field_name', models.CharField(max_length=100)),
                ('file_path', models.CharField(max_length=500)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applications.application')),
            ],
            options={
                'db_table': 'applications_document',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
