# Generated by Django 5.2.6 on 2025-10-25 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_application_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationdocument',
            name='document_type',
        ),
    ]
