# Generated by Django 5.2.6 on 2025-09-24 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('scheme_type', models.CharField(choices=[('CENTRAL', 'Central Government'), ('STATE', 'State Government')], max_length=10)),
                ('category', models.CharField(choices=[('AGRICULTURE', 'Agriculture & Rural Development'), ('EDUCATION', 'Education & Skill Development'), ('HEALTH', 'Health & Nutrition'), ('EMPLOYMENT', 'Employment & Livelihood'), ('HOUSING', 'Housing & Urban Development'), ('SOCIAL_SECURITY', 'Social Security & Welfare'), ('WOMEN_CHILD', 'Women & Child Development'), ('FINANCIAL', 'Financial Services'), ('ENERGY', 'Energy & Environment'), ('TRANSPORT', 'Transport & Infrastructure'), ('OTHER', 'Other')], max_length=20)),
                ('ministry', models.CharField(max_length=100)),
                ('income_groups', models.JSONField(blank=True, default=list)),
                ('applicable_states', models.JSONField(blank=True, default=list)),
                ('age_min', models.PositiveIntegerField(blank=True, null=True)),
                ('age_max', models.PositiveIntegerField(blank=True, null=True)),
                ('gender_applicable', models.JSONField(blank=True, default=list)),
                ('benefits', models.TextField()),
                ('eligibility_details', models.TextField()),
                ('required_documents', models.TextField()),
                ('application_process', models.TextField()),
                ('official_website', models.URLField(blank=True, null=True)),
                ('helpline_number', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('launch_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schemes.scheme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'scheme')},
            },
        ),
    ]
