# Generated by Django 5.2.6 on 2025-10-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='custom_form_fields',
            field=models.JSONField(blank=True, help_text='Custom fields in JSON format: {"custom_fields": [{"field_name": "...", "field_type": "...", ...}]}', null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='form_template',
            field=models.CharField(choices=[('BASIC', 'Basic Form'), ('EDUCATION', 'Education Scheme Form'), ('HEALTH', 'Health Scheme Form'), ('HOUSING', 'Housing Scheme Form'), ('EMPLOYMENT', 'Employment Scheme Form'), ('FINANCIAL', 'Financial Scheme Form'), ('SOCIAL_SECURITY', 'Social Security Form'), ('WOMEN_CHILD', 'Women & Child Welfare Form'), ('AGRICULTURE', 'Agriculture Scheme Form')], default='BASIC', help_text='Select the base form template for this scheme', max_length=50),
        ),
    ]
