# Generated by Django 5.2.6 on 2025-10-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0002_scheme_custom_form_fields_scheme_form_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheme',
            name='custom_form_fields',
        ),
        migrations.RemoveField(
            model_name='scheme',
            name='form_template',
        ),
        migrations.AddField(
            model_name='scheme',
            name='application_fields',
            field=models.JSONField(blank=True, help_text='Custom form fields in JSON format', null=True),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='category',
            field=models.CharField(choices=[('AGRICULTURE', 'Agriculture & Rural Development'), ('EDUCATION', 'Education & Skill Development'), ('HEALTH', 'Health & Nutrition'), ('EMPLOYMENT', 'Employment & Livelihood'), ('HOUSING', 'Housing & Urban Development'), ('SOCIAL_SECURITY', 'Social Security & Welfare'), ('WOMEN_CHILD', 'Women & Child Development'), ('FINANCIAL', 'Financial Services'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterModelTable(
            name='scheme',
            table='schemes_scheme',
        ),
        migrations.AlterModelTable(
            name='userfavorite',
            table='schemes_userfavorite',
        ),
    ]
