# Generated by Django 5.2.6 on 2025-10-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0003_remove_scheme_custom_form_fields_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheme',
            name='application_fields',
        ),
        migrations.AddField(
            model_name='scheme',
            name='custom_form_fields',
            field=models.JSONField(blank=True, help_text='Custom application fields', null=True),
        ),
        migrations.AddField(
            model_name='scheme',
            name='form_template',
            field=models.CharField(blank=True, help_text='Form template name', max_length=50, null=True),
        ),
    ]
